# Generated by Django 4.0.5 on 2022-07-03 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.DateField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, unique=True, verbose_name='Слово')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('example', models.TextField(verbose_name='Пример')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislike', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('word_add_date', models.DateField(auto_now=True, verbose_name='Дата добавления')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Все слова',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UsersMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_add_date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('complaint_add_date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
