# Generated by Django 4.0.5 on 2022-07-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='reg',
            field=models.DateField(auto_now_add=True),
        ),
    ]
