# Generated by Django 4.0.5 on 2022-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_complaint_complaint_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
