# Generated by Django 4.0.5 on 2022-07-02 21:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_add_date',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='fav_add_date',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='reg',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_add_date',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
        migrations.CreateModel(
            name='UsersMars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
