# Generated by Django 4.0.5 on 2022-07-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_complaint_complaint_add_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersMars',
            new_name='UsersMarks',
        ),
    ]
