# Generated by Django 4.0.5 on 2022-07-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_alter_complaint_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_add_date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='word',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.profileuser', verbose_name='Пользователь'),
        ),
    ]
